language: node_js
node_js:
- '10'
- '9'
- '8'
- '6'
deploy:
  provider: npm
  email: luish.faria@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: beeblebrox3/sbee

addons:
  sonarcloud:
    organization: "beeblebrox3-github"
    token:
      secure: $SONAR_TOKEN
script:
  - sonar-scanner
